# Generated by Django 4.2.3 on 2023-07-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="priority",
        ),
    ]
