# Generated by Django 4.2.2 on 2023-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_product_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
