# Generated by Django 4.2.2 on 2023-07-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="priority",
        ),
    ]
