# Generated by Django 4.2.2 on 2023-07-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_productimage_product_secondary_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="secondary_images",
        ),
    ]
