# Generated by Django 4.2.2 on 2023-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_product_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
