# Generated by Django 4.2.2 on 2023-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_rename_image_productimage_subimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="subImage",
            field=models.ImageField(blank=True, null=True, upload_to="subImages/"),
        ),
    ]
